[project]
name = "odoo-addons-oca-stock-logistics-barcode"
version = "18.0.20250206.0"
dependencies = [
    "odoo-addon-product_multi_barcode==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
